# VelocityTabList 插件配置文件
# 作者: XRain
# 项目地址: https://github.com/RMS-Server/velocitybettertablist

# 自动更新配置
auto-update:
  # 是否启用自动更新检查
  enabled: true
  
  # 版本检查间隔（小时）
  check-interval-hours: 24
  
  # 是否自动下载更新
  auto-download: false
  
  # 是否在启动时检查更新
  check-on-startup: true
  
  # GitHub仓库信息
  github-repo: "RMS-Server/velocitybettertablist"
  
  # 自动更新URL（用于获取plugin.version文件）
  version-url: "https://raw.githubusercontent.com/RMS-Server/velocitybettertablist/main/plugin.version"